version: "3.4"

x-pod-template: &pod
  depends_on:
  - pod
  network_mode: service:pod

services:

  pod:
    image: alpine
    command:
    - sh
    - -c
    - while true; do sleep 5; done

  registry:
    <<: *pod
    image: registry:2

  dind:
    <<: *pod
    image: docker:stable-dind
    command:
    - dockerd
    - --host
    - tcp://127.0.0.1:2375
    privileged: true

  console:
    <<: *pod
    image: docker:stable
    command:
    - sh
    - -c
    - while true; do sleep 5; done
